source 'https://rubygems.org'
ruby '>= 2.3.1'

# Middleman
gem 'middleman', '~> 4.3.4'
gem 'middleman-syntax'
gem 'middleman-autoprefixer'
gem 'middleman-sprockets'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.10.10'
